- name: test-task
  hosts: test-vm
  become: yes
  vars:
    php_version: "8.2"
    mysql_apt_config_pkg: mysql-apt-config_0.8.29-1_all.deb 
    pakages:
            - lsb-release
            - gnupg
            - debconf-utils
            - nginx
            - php{{ php_version }}
            - php{{ php_version }}-fpm
  
  tasks:
   - name: Install standard utilities
     block:
      - name: Apt update
        apt:
          update_cache: yes 
      - name: Apt install
        apt:
          pkg: "{{ pakages }}" 
          state: present

   - name: Install mysql-server
     block:
      - name: Debconf field 1
        debconf:
          name: mysql-apt-config
          question: mysql-apt-config/select-product
          value: Ok
          vtype: select
      - name: Debconf field 2
        debconf:
          name: mysql-apt-config
          question: mysql-apt-config/select-server
          value: mysql-8.0
          vtype: select
      - name: Install mysql repository
        shell: export DEBIAN_FRONTEND=noninteractive; wget https://dev.mysql.com/get/{{ mysql_apt_config_pkg }}; dpkg -i {{ mysql_apt_config_pkg }}
      - name: Apt update
        apt:
          update_cache: yes 
      - name: Install server
        apt:
         pkg: mysql-server 
         state: present
         
   - name: Config nginx and php
     block:
      - name: Change nginx default config
        template:
          src: php.conf.j2
          dest: /etc/nginx/sites-available/php.conf
          mode: '0644'
      - name: Create a symbolic link
        file:
          src: /etc/nginx/sites-available/php.conf
          dest: /etc/nginx/sites-enabled/default
          state: link
      - name: Copy info.php
        copy:
          src: info.php
          dest: /var/www/html/info.php
          mode: '0644'
      - name: Reload nginx
        ansible.builtin.systemd_service:
          name: nginx.service
          state: reloaded
          


   



